 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  name: blip_caption
  args:
    max_txt_len: 20
    # adapter
    # adapter_type: "vit"
    # vit encoder
    vit_type: "base"
    # bert config
    med_config_path: "configs/med_config.json"
    # tune language model or not
    # generation configs
    prompt: "a picture of "
  checkpoint_url: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP/blip_coco_caption_base.pth"
  tune_args:
    tune_language: false
